# Generated by Django 5.0.2 on 2024-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urhajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('orszag', models.CharField(max_length=255)),
                ('nem', models.CharField(max_length=1)),
                ('szul', models.IntegerField()),
                ('urido', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Űrhajós',
                'verbose_name_plural': 'Űrhajósok',
            },
        ),
    ]
